"""add tier to ai_memories

Revision ID: 664c01beca64
Revises: f401bb1e2bd2
Create Date: 2026-04-25 11:09:29.628368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664c01beca64'
down_revision: Union[str, None] = 'f401bb1e2bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_memories', sa.Column('tier', sa.Enum('short_term', 'mid_term', 'long_term', 'general', name='ai_memory_tier'), server_default='general', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_memories', 'tier')
    # ### end Alembic commands ###
