"""add day_memories table

Revision ID: 87791e60a624
Revises: d18df8ecd983
Create Date: 2026-04-25 09:20:39.855511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87791e60a624'
down_revision: Union[str, None] = 'd18df8ecd983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_ai', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('intentions', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('completed', sa.Text(), nullable=True),
    sa.Column('gratitude', sa.Text(), nullable=True),
    sa.Column('free_notes', sa.Text(), nullable=True),
    sa.Column('mood', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('mood IS NULL OR (mood >= 1 AND mood <= 5)', name='ck_day_memories_mood_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'is_ai', name='uq_day_memories_date_is_ai')
    )
    op.create_index(op.f('ix_day_memories_date'), 'day_memories', ['date'], unique=False)
    op.create_index(op.f('ix_day_memories_id'), 'day_memories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_memories_id'), table_name='day_memories')
    op.drop_index(op.f('ix_day_memories_date'), table_name='day_memories')
    op.drop_table('day_memories')
    # ### end Alembic commands ###
