"""drop unique on chat_messages tool_call_id

Revision ID: 8c36b21408d0
Revises: 8e90dba08581
Create Date: 2026-04-25 09:45:06.819436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c36b21408d0'
down_revision: Union[str, None] = '8e90dba08581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_chat_messages_chat_tool_call'), table_name='chat_messages')
    op.create_index('ix_chat_messages_chat_tool_call', 'chat_messages', ['chat_id', 'tool_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_chat_tool_call', table_name='chat_messages')
    op.create_index(op.f('uq_chat_messages_chat_tool_call'), 'chat_messages', ['chat_id', 'tool_call_id'], unique=True)
    # ### end Alembic commands ###
