"""add suggested_replies + ai memory tier + user_prompt

Revision ID: f401bb1e2bd2
Revises: 8c36b21408d0
Create Date: 2026-04-25 11:03:06.717561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f401bb1e2bd2'
down_revision: Union[str, None] = '8c36b21408d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('suggested_replies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'suggested_replies')
    # ### end Alembic commands ###
